<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/25 0025
 * Time: 下午 05:30
 */
namespace app\models_ext;
use app\models\SiteConfig;
class SiteConfigExt extends SiteConfig{

    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->created = time();
            $this->updated = time();
        }else{
            $this->updated = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getConfVal(){
        return json_decode($this->config_value);
    }

    public function setConfVal($val){
        $this->config_value = json_encode($val);
    }
}